# -*- coding: utf-8 -*-
"""Worksheet_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zK5pSzikiRPajbWUPAyvwKBBnCRUNxzt
"""

#Problem 1
#Q1
import numpy as np

emp_arr=np.empty((2,2))
print(emp_arr)

#Q2
import numpy as np

arr=np.ones((4,2))
print(arr)

#Q3
import numpy as np

arr=np.full((2,2),2)
print(arr)

#Q4
import numpy as np

given_arr=np.array([[1,2],[3,4]])
zero_arr=np.zeros_like(given_arr)
print(zero_arr)

#Q5
import numpy as np

given_arr=np.array([[1,2],[3,4]])
one_arr=np.ones_like(given_arr)
print(one_arr)

#Q6
import numpy as np

list=[1,2,3,4]
arr=np.array(list)
print(arr)

#Problem 2
#Q1
arr=np.arange(10,50)
print(arr)

#Q2
matrix=np.arange(9).reshape(3,3)
print(matrix)

#Q3
identity_matrix=np.eye(3)
print(identity_matrix)

#Q4
arr=np.random.random(30)
mean=arr.mean()
print(mean)

#Q5
arr=np.random.random((10,10))
min=arr.min()
max=arr.max()
print(f"Min: {min}, Max: {max}")

#Q6
arr=np.zeros(10)
arr[4]=1
print(arr)

#Q7
arr=np.array([1,2,3,4,5,6])
rev_arr=arr[::-1]
print(rev_arr)

#Q8
arr=np.ones((4,4))
arr[1:-1,1:-1]=0
print(arr)

#Q9
checkboard=np.zeros((8,8), dtype=int)
checkboard[1::2,::2]=1
checkboard[::2,1::2]=1
print(checkboard)

#Problem 3
x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
v=np.array([9,10])
w=np.array([11,12])
print("Arrays:")
print(f"x = {x}")
print(f"y = {y}")
print(f"v = {v}")
print(f"w = {w}")

#Q1
add=x+y
print(f"Sum: {add}")

#Q2
sub=x-y
print(f"Difference: {sub}")

#Q3
mul=x*3
print(f"Multiplication: {mul}")

#Q4
sq=x**2
print(f"Square: {sq}")

#Q5
vw=np.dot(v,w)
xv=np.dot(x,v)
xy=np.dot(x,y)
print(f"v.w={vw}")
print(f"x.v={xv}")
print(f"x.y={xy}")

#Q6
row=np.concatenate((x,y),axis=0)
col=np.column_stack((v,w))
print("x and y along rows:")
print(row)
print("v and w along columns:")
print(col)

#Q7
try:
  con_xv=np.concatenate((x,v))
  print("Concatenation Successful")
except ValueError as e:
  print(f"Error: {e}")
  print("Explanation: Arrays have incompatible shapes - x is 2x2 (2D), v is (2,) (1D)")
  print("They must have the same number of dimensions for concatenation")

#Problem 4
import numpy as np

A=np.array([[3,4],[7,8]])
B=np.array([[5,3],[2,1]])

#Q1
try:
  A_inv=np.linalg.inv(A)
  identity=np.dot(A,A_inv)
  print("A · A⁻¹ ≈ I:")
  print("A⁻¹ =")
  print(A_inv)
  print("A · A⁻¹ =")
  print(identity)
  print("Is this close to identity matrix?\n", np.allclose(identity, np.eye(2)))
except np.linalg.LinAlgError:
  print("Matrix A is singular, cannot compute inverse")

#Q.2
AB=np.dot(A,B)
BA=np.dot(B,A)
print("AB̸=BA:")
print(f"AB= {AB}")
print(f"BA={BA}")
print(f"Are they equal? \n{np.array_equal(AB, BA)}")

#Q.3
AB=AB.T
BA=np.dot(B.T,A.T)
print("(AB)ᵀ = BᵀAᵀ:")
print(f"(AB)ᵀ = {AB}")
print(f"BᵀAᵀ = {BA}")
print(f"Are they equal? {np.array_equal(AB, BA)}")

# Solving equation
A = np.array([[2, -3, 1],[1, -1, 2],[3, 1, -1]])
B = np.array([-1, -3, 9])

print("Coefficient matrix A:")
print(A)
print("Constant vector B:")
print(B)

# Method 1: Using Inverse Method
A_inv = np.linalg.inv(A)
X_inv = np.dot(A_inv, B)
print(f"x = {X_inv[0]:.2f}, y = {X_inv[1]:.2f}, z = {X_inv[2]:.2f}")

verification = np.dot(A, X_inv)
print(f"A · X = {verification}")
print(f"B      = {B}")
print(f"Solution correct? {np.allclose(verification, B)}")

# Method 2: Using np.linalg.solve
X_solve = np.linalg.solve(A, B)
print(f"x = {X_solve[0]:.2f}, y = {X_solve[1]:.2f}, z = {X_solve[2]:.2f}")

print(f"2x - 3y + z = {2*X_solve[0] - 3*X_solve[1] + X_solve[2]:.2f} (should be -1)")
print(f"x - y + 2z = {X_solve[0] - X_solve[1] + 2*X_solve[2]:.2f} (should be -3)")
print(f"3x + y - z = {3*X_solve[0] + X_solve[1] - X_solve[2]:.2f} (should be 9)")

# Check if both methods give the same result
print(f"\nBoth methods give same result? {np.allclose(X_inv, X_solve)}")

import time

size = 100000
matrix_size = 100

# 1. Element-wise Addition
list1 = list(range(size))
list2 = list(range(size, 2*size))

start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
python_add_time = time.time() - start_time
print(f"Python Lists: {python_add_time:.4f} seconds")

arr1 = np.arange(size)
arr2 = np.arange(size, 2*size)

start_time = time.time()
result_numpy = arr1 + arr2
numpy_add_time = time.time() - start_time
print(f"NumPy Arrays: {numpy_add_time:.4f} seconds")
print(f"NumPy is {python_add_time/numpy_add_time:.1f}x faster\n")

# 2. Element-wise Multiplication

start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
python_mult_time = time.time() - start_time
print(f"Python Lists: {python_mult_time:.4f} seconds")

start_time = time.time()
result_numpy = arr1 * arr2
numpy_mult_time = time.time() - start_time
print(f"NumPy Arrays: {numpy_mult_time:.4f} seconds")
print(f"NumPy is {python_mult_time/numpy_mult_time:.1f}x faster\n")

# 3. Dot Product

start_time = time.time()
dot_product = sum(list1[i] * list2[i] for i in range(size))
python_dot_time = time.time() - start_time
print(f"Python Lists: {python_dot_time:.4f} seconds")

start_time = time.time()
dot_product_numpy = np.dot(arr1, arr2)
numpy_dot_time = time.time() - start_time
print(f"NumPy Arrays: {numpy_dot_time:.4f} seconds")
print(f"NumPy is {python_dot_time/numpy_dot_time:.1f}x faster\n")

# 4. Matrix Multiplication (SIMPLIFIED VERSION)
print("4. MATRIX MULTIPLICATION")

small_matrix_size = 50
matrix1 = [[i + j for j in range(small_matrix_size)] for i in range(small_matrix_size)]
matrix2 = [[i - j for j in range(small_matrix_size)] for i in range(small_matrix_size)]

print("Calculating Python matrix multiplication (this may take a few seconds)...")
start_time = time.time()
result_matrix = [[0 for _ in range(small_matrix_size)] for _ in range(small_matrix_size)]
for i in range(small_matrix_size):
    for j in range(small_matrix_size):
        for k in range(small_matrix_size):
            result_matrix[i][j] += matrix1[i][k] * matrix2[k][j]
python_matrix_time = time.time() - start_time
print(f"Python Lists: {python_matrix_time:.4f} seconds")

np_matrix1 = np.random.rand(matrix_size, matrix_size)
np_matrix2 = np.random.rand(matrix_size, matrix_size)

start_time = time.time()
result_numpy_matrix = np.matmul(np_matrix1, np_matrix2)
numpy_matrix_time = time.time() - start_time
print(f"NumPy Arrays: {numpy_matrix_time:.4f} seconds")

python_per_element = python_matrix_time / (small_matrix_size ** 3)
numpy_per_element = numpy_matrix_time / (matrix_size ** 3)
speed_factor = python_per_element / numpy_per_element

print(f"NumPy is approximately {speed_factor:.0f}x faster per operation")

print("NumPy is significantly faster for mathematical operations!")