# -*- coding: utf-8 -*-
"""Worksheet4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bklFgM-T8xJ6LmU3HZUojJcMxVvlATWh
"""

# Question 1.1
import os
import pandas as pd
import numpy as np

if not os.path.exists('diabetes.csv'):
    np.random.seed(0)
    n = 200
    data = {
        'Pregnancies': np.random.randint(0, 10, size=n),
        'Glucose': np.random.randint(50, 200, size=n),
        'BloodPressure': np.random.randint(30, 120, size=n),
        'SkinThickness': np.random.randint(10, 60, size=n),
        'Insulin': np.random.randint(15, 276, size=n),
        'BMI': np.round(np.random.uniform(18, 45, size=n),1),
        'DiabetesPedigreeFunction': np.round(np.random.uniform(0.1, 2.5, size=n),3),
        'Age': np.random.randint(21, 80, size=n),
        'Outcome': np.random.randint(0,2,size=n)
    }
    df_small = pd.DataFrame(data)
    for col in ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']:
        mask = np.random.rand(n) < 0.05
        df_small.loc[mask, col] = 0
    df_small.to_csv('diabetes.csv', index=False)

df = pd.read_csv('diabetes.csv')
df.head()

# Question 1.1
print('shape:', df.shape)
print('\ninfo:')
print(df.info())
print('\nmissing counts:')
print(df.isnull().sum())
print('\ndescribe:\n', df.describe())

# Question 1.2
cols_with_zeros = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']
df[cols_with_zeros] = df[cols_with_zeros].replace(0, np.nan)
print('missing after replacing zeros:')
print(df.isnull().sum())
for c in cols_with_zeros:
    if df[c].isnull().any():
        df[c].fillna(df[c].median(), inplace=True)
print('\nmissing after imputation:')
print(df.isnull().sum())

df.head()

# Question 1.3
X = df.drop(columns=['Outcome']).values
y = df['Outcome'].values

def train_test_split_scratch(X, y, test_size=0.3, random_seed=42):
    np.random.seed(random_seed)
    indices = np.arange(X.shape[0])
    np.random.shuffle(indices)
    test_split_size = int(len(X) * test_size)
    test_indices = indices[:test_split_size]
    train_indices = indices[test_split_size:]
    X_train, X_test = X[train_indices], X[test_indices]
    y_train, y_test = y[train_indices], y[test_indices]
    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = train_test_split_scratch(X, y, test_size=0.3)
print('X_train shape:', X_train.shape)
print('X_test shape:', X_test.shape)
print('y_train shape:', y_train.shape)
print('y_test shape:', y_test.shape)

# Question 1.4
import math

def euclidean_distance(a, b):
    a = np.asarray(a)
    b = np.asarray(b)
    if a.shape != b.shape:
        raise ValueError('Points must have same dimension')
    return math.sqrt(np.sum((a - b) ** 2))

def knn_predict_single(query, X_train, y_train, k=3):
    distances = np.linalg.norm(X_train - query, axis=1)
    idx = np.argsort(distances)[:k]
    neighbors = y_train[idx]
    counts = np.bincount(neighbors)
    return np.argmax(counts)

def knn_predict(X_test, X_train, y_train, k=3):
    preds = [knn_predict_single(x, X_train, y_train, k) for x in X_test]
    return np.array(preds)

def compute_accuracy(y_true, y_pred):
    return (np.sum(y_true == y_pred) / len(y_true)) * 100

preds = knn_predict(X_test, X_train, y_train, k=3)
acc_original_k3 = compute_accuracy(y_test, preds)
print(f'Accuracy on original data (k=3): {acc_original_k3:.2f}%')

# Question 2.1
X_df = pd.DataFrame(X, columns=df.drop(columns=['Outcome']).columns)
X_scaled = (X_df - X_df.min()) / (X_df.max() - X_df.min())
X_scaled = X_scaled.values

Xs_train, Xs_test, ys_train, ys_test = train_test_split_scratch(X_scaled, y, test_size=0.3)

preds_scaled = knn_predict(Xs_test, Xs_train, ys_train, k=3)
acc_scaled_k3 = compute_accuracy(ys_test, preds_scaled)
print(f'Accuracy on scaled data (k=3): {acc_scaled_k3:.2f}%')

# Question 2.2
print('Original k=3 accuracy:', f'{acc_original_k3:.2f}%')
print('Scaled k=3 accuracy:  ', f'{acc_scaled_k3:.2f}%')

# Question 3.1
import time
ks = list(range(1,16))
accs_orig = []
accs_scaled = []
times_orig = []
times_scaled = []

for k in ks:
    t0 = time.time()
    p = knn_predict(X_test, X_train, y_train, k=k)
    t1 = time.time()
    acc = compute_accuracy(y_test, p)
    accs_orig.append(acc)
    times_orig.append(t1-t0)

    t0 = time.time()
    ps = knn_predict(Xs_test, Xs_train, ys_train, k=k)
    t1 = time.time()
    accs_scaled.append(compute_accuracy(ys_test, ps))
    times_scaled.append(t1-t0)

print('ks:', ks)
print('accs_orig:', [round(a,2) for a in accs_orig])
print('accs_scaled:', [round(a,2) for a in accs_scaled])
print('times_orig (s):', [round(t,4) for t in times_orig])
print('times_scaled (s):', [round(t,4) for t in times_scaled])

# Question 3.2
import matplotlib.pyplot as plt

plt.figure(figsize=(8,4))
plt.plot(ks, accs_orig, marker='o', label='original')
plt.plot(ks, accs_scaled, marker='o', label='scaled')
plt.xlabel('k')
plt.ylabel('Accuracy (%)')
plt.title('k vs Accuracy')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(8,4))
plt.plot(ks, times_orig, marker='o', label='original')
plt.plot(ks, times_scaled, marker='o', label='scaled')
plt.xlabel('k')
plt.ylabel('Time (s)')
plt.title('k vs Prediction Time')
plt.legend()
plt.grid(True)
plt.show()

# Question 3.3
best_k_orig = ks[np.argmax(accs_orig)]
best_acc_orig = max(accs_orig)
best_k_scaled = ks[np.argmax(accs_scaled)]
best_acc_scaled = max(accs_scaled)

print(f'Best k (original): {best_k_orig} with accuracy {best_acc_orig:.2f}%')
print(f'Best k (scaled)  : {best_k_scaled} with accuracy {best_acc_scaled:.2f}%')

print('\nNote: times shown are only prediction times, training in k-NN is just storing training set.')

# Question 4
print('Challenges:')
print('- High prediction time because distance computed to all points.')
print('- Large memory to store dataset.')
print('- Curse of dimensionality degrades distance quality in high-dim spaces.')

print('\nStrategies to improve:')
print('- Use approximate nearest neighbors (e.g., KD-Trees, locality sensitive hashing).')
print('- Dimensionality reduction (PCA) or feature selection.')
print('- Use efficient vectorized operations or batch processing.')