# -*- coding: utf-8 -*-
"""Worksheet_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yvmZ8okfjuvGkOlSeHLZ61dbDki-47ll
"""

from google.colab import drive
drive.mount('/content/drive')

# To-Do 1
import numpy as np
import pandas as pd

data = pd.read_csv("/content/drive/MyDrive/student.csv")

print(data.head())
print(data.tail())
print(data.info())
print(data.describe())

X = data[["Math", "Reading"]].values
Y = data["Writing"].values

# To-Do 2
X_matrix = X.T
Y_matrix = Y

W = np.zeros((X.shape[0], 1))  # Shape: (2, 1)

print("X shape:", X.shape)
print("Y shape:", Y.shape)
print("W shape:", W.shape)

#To-do 3
from random import shuffle

def train_test_split_scratch(X, y, test_size=0.3, random_seed=42):
    """Custom train-test split using only Python's random module"""
    import random
    random.seed(random_seed)

    n = len(X)
    indices = list(range(n))
    shuffle(indices)

    test_split = int(n * test_size)
    test_idx = indices[:test_split]
    train_idx = indices[test_split:]

    X_train = X[train_idx]
    X_test = X[test_idx]
    y_train = y[train_idx]
    y_test = y[test_idx]

    return X_train, X_test, y_train, y_test

import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/student.csv')
X = data[['Math', 'Reading']].values
y = data['Writing'].values

X_train, X_test, y_train, y_test = train_test_split_scratch(X, y, test_size=0.20)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

# To-Do 4
def cost_function(X, Y, W):
    """
    Compute Mean Squared Error (MSE).
    X: (m, d) feature matrix
    Y: (m, 1) target vector
    W: (d, 1) weight matrix
    """
    m = X.shape[0]
    Y_pred = X.dot(W)  # (m, 1)
    cost = (1/(2*m)) * np.sum((Y_pred - Y) ** 2)
    return cost

# To-Do 5
X_test_case = np.array([[1, 2], [3, 4], [5, 6]])
Y_test_case = np.array([3, 7, 11])
W_test_case = np.array([1, 1])

cost = cost_function(X_test_case, Y_test_case, W_test_case)

if cost == 0:
    print("Proceed Further")
else:
    print("something went wrong")

print("Cost function output:", cost)

# To-Do 6
def gradient_descent(X, Y, W, alpha, iterations):
    cost_history = [0] * iterations
    m = len(Y)

    for i in range(iterations):
        Y_pred = np.dot(X, W)
        loss = Y_pred - Y
        dw = np.dot(X.T, loss) / m
        W = W - alpha * dw
        cost_history[i] = cost_function(X, Y, W)

    return W, cost_history

# To-Do 7
np.random.seed(0)

X = np.random.rand(100, 3)
Y = np.random.rand(100)
W = np.random.rand(3)

alpha = 0.01
iterations = 1000

final_params, cost_history = gradient_descent(X, Y, W, alpha, iterations)

print("Final Parameters:", final_params)
print("Cost History:", cost_history)

# To-Do 8
def rmse(Y, Y_pred):
    return np.sqrt(np.mean((Y - Y_pred) ** 2))

# To-Do 9
def r2(Y, Y_pred):
    mean_y = np.mean(Y)
    ss_tot = np.sum((Y - mean_y) ** 2)
    ss_res = np.sum((Y - Y_pred) ** 2)
    return 1 - (ss_res / ss_tot)

# To-Do 10
def main():
    data = pd.read_csv("/content/drive/MyDrive/student.csv")

    X = data[["Math", "Reading"]].values
    Y = data["Writing"].values

    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

    W = np.zeros(X_train.shape[1])
    alpha = 0.00001
    iterations = 1000

    W_optimal, cost_history = gradient_descent(X_train, Y_train, W, alpha, iterations)

    Y_pred = np.dot(X_test, W_optimal)

    model_rmse = rmse(Y_test, Y_pred)
    model_r2 = r2(Y_test, Y_pred)

    print("Final Weights:", W_optimal)
    print("Cost History (First 10):", cost_history[:10])
    print("RMSE:", model_rmse)
    print("R2:", model_r2)

main()